[package]
name = "web3_verif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18.0"
hex = "0.4.3"
rocket = "0.4.11"
try-catch = "0.2.2"